-- MySQL Script generated by MySQL Workbench
-- Sun Mar  8 20:11:13 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Curso` (
  `ID_curso` INT NOT NULL,
  `nomeCurso` VARCHAR(100) NULL,
  `turno` VARCHAR(20) NULL,
  PRIMARY KEY (`ID_curso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `ID_matriculaProfessor` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `departamento` VARCHAR(50) NULL,
  `nivel_de_formacao` VARCHAR(50) NULL,
  PRIMARY KEY (`ID_matriculaProfessor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
  `ID_AlunoMatricula` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `alunoCPF` VARCHAR(14) NULL,
  `AlunoDOB` DATE NULL,
  `nomePai` VARCHAR(100) NULL,
  `nomeMae` VARCHAR(100) NULL,
  `ID_cursoFK` INT NOT NULL,
  PRIMARY KEY (`ID_AlunoMatricula`, `ID_cursoFK`),
  INDEX `fk_Aluno_Curso1_idx` (`ID_cursoFK` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_Curso1`
    FOREIGN KEY (`ID_cursoFK`)
    REFERENCES `mydb`.`Curso` (`ID_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contrato_de_Trabalho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contrato_de_Trabalho` (
  `ID_contrato` INT NOT NULL,
  `tipo_de_vinculo` VARCHAR(50) NULL,
  `carga_horaria_semanal` INT NULL,
  PRIMARY KEY (`ID_contrato`),
  UNIQUE INDEX `ID_contrato_UNIQUE` (`ID_contrato` ASC) VISIBLE,
  CONSTRAINT `ID_matriculaProfessor`
    FOREIGN KEY (`ID_contrato`)
    REFERENCES `mydb`.`Professor` (`ID_matriculaProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prontuario_Academico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prontuario_Academico` (
  `ID_AlunoMatriculaProntuario` INT NOT NULL,
  `data_de_matricula` DATE NULL,
  `situacao` VARCHAR(20) NULL,
  PRIMARY KEY (`ID_AlunoMatriculaProntuario`),
  INDEX `fk_Prontuario_Academico_Aluno1_idx` (`ID_AlunoMatriculaProntuario` ASC) VISIBLE,
  CONSTRAINT `fk_Prontuario_Academico_Aluno1`
    FOREIGN KEY (`ID_AlunoMatriculaProntuario`)
    REFERENCES `mydb`.`Aluno` (`ID_AlunoMatricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Leciona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Leciona` (
  `ID_curso` INT NOT NULL,
  `ID_matriculaProfessor` INT NOT NULL,
  `semestre` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID_curso`, `ID_matriculaProfessor`, `semestre`),
  INDEX `ID_matriculaProfessor_idx` (`ID_matriculaProfessor` ASC) VISIBLE,
  CONSTRAINT `ID_curso`
    FOREIGN KEY (`ID_curso`)
    REFERENCES `mydb`.`Curso` (`ID_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_matriculaProfessor`
    FOREIGN KEY (`ID_matriculaProfessor`)
    REFERENCES `mydb`.`Professor` (`ID_matriculaProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProfessoresCursosAssociativeTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProfessoresCursosAssociativeTable` (
  `Curso_ID_curso` INT NOT NULL,
  `Professor_ID_matriculaProfessor` INT NOT NULL,
  `Semestre` VARCHAR(10) NULL,
  PRIMARY KEY (`Curso_ID_curso`, `Professor_ID_matriculaProfessor`),
  INDEX `fk_Curso_has_Professor_Professor1_idx` (`Professor_ID_matriculaProfessor` ASC) VISIBLE,
  INDEX `fk_Curso_has_Professor_Curso1_idx` (`Curso_ID_curso` ASC) VISIBLE,
  CONSTRAINT `fk_Curso_has_Professor_Curso1`
    FOREIGN KEY (`Curso_ID_curso`)
    REFERENCES `mydb`.`Curso` (`ID_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Curso_has_Professor_Professor1`
    FOREIGN KEY (`Professor_ID_matriculaProfessor`)
    REFERENCES `mydb`.`Professor` (`ID_matriculaProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
